name: Check that the ROM can be built

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest (The build is flaky there because of #1, unfortunately.)
      fail-fast: false
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Install RGBDS (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir rgbds
        curl -L https://github.com/gbdev/rgbds/releases/download/v0.9.1/rgbds-0.9.1-linux-x86_64.tar.xz | tar xJC rgbds
        cd rgbds
        sudo ./install.sh
    - name: Install RGBDS and Make (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install rgbds make
        printf 'PATH=/opt/homebrew/opt/make/libexec/gnubin:%s\n' "$PATH" | tee -a "$GITHUB_ENV"
    - name: Install RGBDS (Windows)
      if: matrix.os == 'windows-latest'
      shell: bash
      run: | # RGBDS needs to go into that directory to be picked up by Make as `rgb*` instead of needing `rgb*.exe`.
        mkdir rgbds
        curl -LOJ https://github.com/gbdev/rgbds/releases/download/v0.9.1/rgbds-0.9.1-win64.zip
        unzip -d /c/mingw64/bin rgbds-0.9.1-win64.zip
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build
      run: make
    - name: Upload the ROM
      uses: actions/upload-artifact@v4
      with:
        name: ROM (${{matrix.os}})
        path: bin
